### GAMES

In [2]:
from scipy.stats import norm
from scipy import stats
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [91]:
stats.t.ppf(0.005, 9)

-3.2498355440153697

In [80]:
y = math.sqrt(10)

In [81]:
y

3.1622776601683795

In [29]:
1.5/(13.3/x)

0.3566478564099676

### ПРОБЛЕМНАЯ ЗАДАЧА

In [69]:
m = 200
n = 10
x = np.array([202, 203, 199, 197, 195, 201, 200, 204, 194, 190])

In [67]:
w = [(x-m)**2 for x in x]
print(w)
numerator = sum(w)
numerator

[4, 9, 1, 9, 25, 1, 0, 16, 36, 100]


201

In [70]:
D = numerator/(n-1) # вручную расчитанная дисперсия
D

22.333333333333332

In [71]:
SE = D**0.5
SE

4.725815626252608

In [79]:
disp = np.var(x,ddof=1)
disp1 = np.var(x,ddof=2)
SE1 = disp**0.5
SE2 = disp1**0.5
disp, SE, disp1, SE1

(19.833333333333332, 4.725815626252608, 22.3125, 4.453463071962462)

In [77]:
stats.ttest_1samp(x, m)

Ttest_1sampResult(statistic=-1.0651074037450894, pvalue=0.31456660352472854)

### Задача (семинар 8)
a = np.array([12, 10, 11, 19, 13, 11, 17, 15, 19, 14, 21, 18, 21, 11, 17, 14, 15, 17, 20, 19])<br>
b = np.array([11, 13, 18, 15, 17, 18, 10, 21, 26, 15, 11, 12, 15, 17, 10, 18, 18, 12,21, 20])<br>
*Провести двусторонний тест и ответить на вопрос, есть ли статистически значимые различия между средними 2х нормально распределенных генеральных совокупностей, представленных следующими независимыми выборками.<br>
**Уровень статистической значимости принять за 5%. Используйте функцию в Python.**

In [3]:
a = np.array([12, 10, 11, 19, 13, 11, 17, 15, 19, 14, 21, 18, 21, 11, 17, 14, 15, 17, 20, 19])

b = np.array([11, 13, 18, 15, 17, 18, 10, 21, 26, 15, 11, 12, 15, 17, 10, 18, 18, 12,21, 20])

In [4]:
stats.ttest_ind(a, b)

Ttest_indResult(statistic=-0.1599663264228627, pvalue=0.8737549039369696)

In [7]:
stats.t.ppf(0.025, 38) # t-расчетное для ddof= 2*(n-1)= 38

-2.0243941645751367

In [10]:
stats.t.cdf(-0.1599663264228627, 38) ## площадь кривой нормального распределения ниже левой границы

0.4368774519684848

In [12]:
##Односторонний t-тест гипотеза a>b
stats.ttest_ind(a, b, alternative='greater', equal_var=True)

Ttest_indResult(statistic=-0.1599663264228627, pvalue=0.5631225480315152)

In [15]:
##Односторонний t-тест гипотеза a<b
stats.ttest_ind(a, b, alternative='less', equal_var=True)

Ttest_indResult(statistic=-0.1599663264228627, pvalue=0.4368774519684848)

**Спортсмен стреляет по мишени. Вероятность попадания в 1 сектор 0.4, во второй -0.3. Какова вероятность попадания в 1 ИЛИ 2 сектор.**
***"ИЛИ"*** - сложение вероятностей. Ответ 0.3+0.4 = **0.7**

----
В группе 21 студент: 5 отличников, 10 хорошистов, 6 слабых. На предстоящем экзамене отлично могут получить только отличники, хорошисты с равной вероятностью могут получить хорошо или отлично, слабые - с одинаковой вероятностью могут получить хорошо, удовлетворительно или неуд. На экзамен вызывается наугад 1 студент. Какова вероятность, что он получит хорошо или отлично.
Ответ: $\frac{5}{21}*1+\frac{10}{21}*1+\frac{6}{21}*\frac{1}{3}$<br>
*для слабых вероятность искомого события 1/3 (если только "хорошо")

---
Некоторое изделие выпускается 2-мя заводами. При этом объем продукции 2 завода в 3 раза превосходит объем продукции 1-го. Доля брака у 1-го - 2%, у 2-го - 1%. Изделие выпущено заводами за одинаковый промежуток времени. Изделия перемешали и отправили в продажу. Какова вероятность, что приобретенное изделие со 2-го завода, если оно бракованное?<br>
$P (A \mid B) = \frac{P(B \mid A)*P(B)}{P(A)}$ *формула БАЙЕСА<br>
*A - брак, В - изделие со 2-го завода, P(B) = 3/4 (0.75), P(A|B) = 0.01, P(A) = 0.25*0.02+0.75*0.01 = 0.0125 (вероятность вытащить * вероятность брака)<br>
___

### Correlation

In [92]:
o = np.array([27, 37, 42, 48, 57, 56, 77, 80])

In [101]:
p = np.array([1.2, 1.6, 1.8, 1.8, 2.5, 2.6, 3.0, 3.3])

In [102]:
print(len(p))

8


In [103]:
np.corrcoef(o, p)

array([[1.        , 0.97857682],
       [0.97857682, 1.        ]])

#### Отсутствие корреляции между двумя величинами еще не говорит о том, что между показателями нет связи.

In [2]:
x = np.array([0, -1, 1, -2, 2, -3, 3, -4, 4])

In [3]:
y = [x**2 for x in x]
y

[0, 1, 1, 4, 4, 9, 9, 16, 16]

In [4]:
np.corrcoef(x, y)

array([[1., 0.],
       [0., 1.]])

In [ ]:
plt.scatter(x, y)
plt.show;

### Covariation

In [59]:
p = np.array([1.2, 1.6, 1.8, 1.8, 2.5, 2.6, 3.0, 3.3])
s = np.array([27, 37, 42, 48, 57, 56, 77, 88])

In [25]:
cov = np.mean(p*s) - np.mean(p)*np.mean(s)
cov

12.737500000000011

In [56]:
54*2.22

119.88000000000001

In [54]:
g = np.mean(p*s)
h = np.mean(p)
j = np.mean(s)
g, h, j

(132.8875, 2.2249999999999996, 54.0)

In [34]:
a = np.cov(p,s, ddof=0) # смещенная ковариация
b = np.cov(p,s, ddof=1) # несмещенная, по умолчанию,если ddof не указано
a, b

(array([[  0.471875,  12.7375  ],
        [ 12.7375  , 362.      ]]),
 array([[  0.53928571,  14.55714286],
        [ 14.55714286, 413.71428571]]))

In [37]:
std1 = np.std(p)
std2 = np.std(s)
std3 = np.std(p, ddof=1)
std4 = np.std(s, ddof=1)
std1, std2, std3, std4

(0.6869315832017042,
 19.026297590440446,
 0.7343607521414215,
 20.339967692065926)

In [38]:
12.7375 / (std1*std2)

0.974577604629697

In [39]:
14.5571 / (std3*std4)

0.9745747354120188

In [28]:
np.corrcoef(p,s) #коэффициент Пирсона или нормированная ковариация

array([[1.       , 0.9745776],
       [0.9745776, 1.       ]])

$cov_{xy} = M(XY)-M(X)*M(Y)$ <br>Ковариация - величина, определяющая зависимость 2 случайных величин<br> 
<br>$r_{xy} = \frac {cov_{xy}}{\sigma_x * \sigma_y}$ коэф.Пирсона

Коэффициент корреляции Спирмена – это ранговый коэффициент корреляции, также показывает тесноту линейной связи, но в отличии от коэффициента корреляции Пирсона не требует нормальности распределений случайных величин и применяется для порядковых и количественных данных.

In [40]:
stats.spearmanr(p, s)

SpearmanrResult(correlation=0.9700772721497398, pvalue=6.548558831120599e-05)

In [41]:
s, p

(array([27, 37, 42, 48, 57, 56, 77, 88]),
 array([1.2, 1.6, 1.8, 1.8, 2.5, 2.6, 3. , 3.3]))

In [51]:
s2 = np.array([1, 2, 3, 4, 6, 5, 7, 8])
p2 = np.array([1, 2, 3.5, 3.5, 5, 6, 7, 8])

In [53]:
np.corrcoef(s2, p2) # расчет коэф.Спирмана вручную

array([[1.        , 0.97007727],
       [0.97007727, 1.        ]])

In [42]:
s3 = np.linalg.matrix_rank(s)
s

array([27, 37, 42, 48, 57, 56, 77, 88])

In [48]:
values = [0.1, 0.9, 0.8, 0.65, 0.2, 0.7]
#Create a copy of the list
vals = values[:]
print(vals)
for i in range(len(vals)):
    m = max(vals)
    print(i+1,'-',values.index(m),'-',m)
    vals.remove(m)

[0.1, 0.9, 0.8, 0.65, 0.2, 0.7]
1 - 1 - 0.9
2 - 2 - 0.8
3 - 5 - 0.7
4 - 3 - 0.65
5 - 4 - 0.2
6 - 0 - 0.1


In [75]:
indices = np.argsort(values)[::-1]
ranks = [i+1 for i in indices]
print(ranks)

for i in range(len(values)):
    print(i+1,'-',ranks[i],'-',values[indices[i]])

[2, 3, 6, 4, 5, 1]
1 - 2 - 0.9
2 - 3 - 0.8
3 - 6 - 0.7
4 - 4 - 0.65
5 - 5 - 0.2
6 - 1 - 0.1
